### ISSUE TITLE
About start tachyon on ec2

### ISSUE THREAD

**Issue by henryon** [amplab/tachyon#2260]
Hey all,

I'm working on deploy techyon on ec2. but found below error. seems some bugs?
An error occurred while executing multiple actions in parallel.
Any errors that occurred are shown below.

btw, I modified some value of conf/ec2.yml with my prefer setting. like ami,vpc-id,subnet-id,az,keypair,keypath.

I am sure the key exist on my local machine #Mac OS ~/.ssh/tachyon.pem 
Any suggestions or support for this case, Thanks in advance.

Error logs#############################

An unexpected error occurred when executing the action on the
'TachyonMaster' machine. Please report this as a bug:

The key pair 'tachyon.pem' does not exist

/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call'
/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/var/root/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/var/root/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/compute.rb:525:in `_request'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/compute.rb:520:in `request'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/requests/compute/run_instances.rb:139:in `run_instances'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/models/compute/servers.rb:158:in `save_many'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/models/compute/server.rb:201:in `save'
/var/root/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/collection.rb:51:in `create'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:102:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

An unexpected error occurred when executing the action on the
'TachyonWorker1' machine. Please report this as a bug:

The key pair 'tachyon.pem' does not exist

/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/expects.rb:6:in `response_call'
/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/middlewares/response_parser.rb:8:in `response_call'
/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:372:in `response'
/var/root/.vagrant.d/gems/gems/excon-0.45.4/lib/excon/connection.rb:236:in `request'
/var/root/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/sax_parser_connection.rb:35:in `request'
/var/root/.vagrant.d/gems/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:7:in `request'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/compute.rb:525:in `_request'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/compute.rb:520:in `request'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/requests/compute/run_instances.rb:139:in `run_instances'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/models/compute/servers.rb:158:in `save_many'
/var/root/.vagrant.d/gems/gems/fog-aws-0.7.6/lib/fog/aws/models/compute/server.rb:201:in `save'
/var/root/.vagrant.d/gems/gems/fog-core-1.35.0/lib/fog/core/collection.rb:51:in `create'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/run_instance.rb:102:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/elb_register_instance.rb:16:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/warn_networks.rb:14:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:86:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/var/root/.vagrant.d/gems/gems/vagrant-aws-0.6.0/lib/vagrant-aws/action/connect_aws.rb:43:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by aaudiber** [comment]
Hi Henry,

Are you sure the key pair was created in the same region that you are
deploying to? The region you are deploying to is specified in ec2.yml
<https://github.com/amplab/tachyon/blob/master/deploy/vagrant/conf/ec2.yml.template#L102>.
If
you create a key in us-west it wouldn't be found in us-east. There are also
some key pair troubleshooting instructions here
<http://docs.aws.amazon.com/AutoScaling/latest/DeveloperGuide/ts-as-instancelaunchfailure.html#ts-as-instancelaunchfailure-2>
?

Hope that helps,
Andrew

On Sun, Dec 13, 2015 at 12:12 AM, HenryOn <notifications@github.com> wrote:

> Hey all,
>
> I'm working on deploy techyon on ec2 but found below error seems some bugs?
> An error occurred while executing multiple actions in parallel
> Any errors that occurred are shown below
>
> btw, I modified some value of conf/ec2yml with my prefer setting like
> ami,vpc-id,subnet-id,az,keypair,keypath
>
> I am sure the key exist on my local machine #Mac OS ~/ssh/tachyonpem
> Any suggestions or support for this case, Thanks in advance
>
> Error logs#############################
>
> An unexpected error occurred when executing the action on the
> 'TachyonMaster' machine Please report this as a bug:
>
> The key pair 'tachyonpem' does not exist
>
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/middlewares/expectsrb:6:in
> response_call'
>
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/middlewares/response_parserrb:8:in
> response_call'
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/connectionrb:372:in
> response'
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/connectionrb:236:in
> request'
> /var/root/vagrantd/gems/gems/fog-xml-012/lib/fog/xml/sax_parser_connectionrb:35:in
> request'
> /var/root/vagrantd/gems/gems/fog-xml-012/lib/fog/xml/connectionrb:7:in
> request'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/computerb:525:in
> _request'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/computerb:520:in
> request'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/requests/compute/run_instancesrb:139:in
> run_instances'
>
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/models/compute/serversrb:158:in
> save_many'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/models/compute/serverrb:201:in
> save'
> /var/root/vagrantd/gems/gems/fog-core-1350/lib/fog/core/collectionrb:51:in
> create'
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/run_instancerb:102:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/elb_register_instancerb:16:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/warn_networksrb:14:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/synced_foldersrb:86:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/provisionrb:80:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:95:in
> block in finalize_action'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builderrb:116:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/util/busyrb:19:in
> busy'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> run'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/callrb:53:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/connect_awsrb:43:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/config_validaterb:25:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/handle_boxrb:56:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builderrb:116:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/util/busyrb:19:in
> busy'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> run'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:214:in
> action_raw'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:191:in block
> in action'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/environmentrb:516:in
> lock'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:178:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:178:in
> action'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/batch_actionrb:82:in
> `block (2 levels) in run'
>
> An unexpected error occurred when executing the action on the
> 'TachyonWorker1' machine Please report this as a bug:
>
> The key pair 'tachyonpem' does not exist
>
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/middlewares/expectsrb:6:in
> response_call'
>
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/middlewares/response_parserrb:8:in
> response_call'
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/connectionrb:372:in
> response'
> /var/root/vagrantd/gems/gems/excon-0454/lib/excon/connectionrb:236:in
> request'
> /var/root/vagrantd/gems/gems/fog-xml-012/lib/fog/xml/sax_parser_connectionrb:35:in
> request'
> /var/root/vagrantd/gems/gems/fog-xml-012/lib/fog/xml/connectionrb:7:in
> request'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/computerb:525:in
> _request'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/computerb:520:in
> request'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/requests/compute/run_instancesrb:139:in
> run_instances'
>
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/models/compute/serversrb:158:in
> save_many'
> /var/root/vagrantd/gems/gems/fog-aws-076/lib/fog/aws/models/compute/serverrb:201:in
> save'
> /var/root/vagrantd/gems/gems/fog-core-1350/lib/fog/core/collectionrb:51:in
> create'
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/run_instancerb:102:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/elb_register_instancerb:16:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/warn_networksrb:14:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/synced_foldersrb:86:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/provisionrb:80:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:95:in
> block in finalize_action'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builderrb:116:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/util/busyrb:19:in
> busy'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> run'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/callrb:53:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /var/root/vagrantd/gems/gems/vagrant-aws-060/lib/vagrant-aws/action/connect_awsrb:43:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/config_validaterb:25:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builtin/handle_boxrb:56:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/wardenrb:34:in
> call'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/builderrb:116:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> block in run'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/util/busyrb:19:in
> busy'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/action/runnerrb:66:in
> run'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:214:in
> action_raw'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:191:in block
> in action'
>
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/environmentrb:516:in
> lock'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:178:in
> call'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/machinerb:178:in
> action'
> /opt/vagrant/embedded/gems/gems/vagrant-174/lib/vagrant/batch_actionrb:82:in
> `block (2 levels) in run'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/amplab/tachyon/issues/2260>.
>



-- 
Andrew Audibert
Software Engineer, Tachyon Nexus, Inc. <http://tachyonnexus.com/>

**Comment by haoyuan** [comment]
Thanks for the questions @henryon ; Please file and track issues in JIRA https://tachyon.atlassian.net/browse/TACHYON/ , and post questions in user forum: https://groups.google.com/forum/?fromgroups#!forum/tachyon-users

Thanks.
