### ISSUE TITLE
Would you please add http server for tachyon?

### ISSUE THREAD

**Issue by netroby** [amplab/tachyon#2393]
Would you please add http server for tachyon?
May we using tachyon as a distribute image storage ? 
but we need http/https/http2 server. to let user access these file via http /https /http2 request.
For example, we storage a image call demo.jpg with tachyon.
we want to access these file via 
```
http://ip-address:8080/path/to/demo.jpg
```

**Comment by yupeng9** [comment]
@netroby, could you post the question in user forum: https://groups.google.com/forum/?fromgroups#!forum/tachyon-users ? 
Or file an issue in JIRA https://tachyon.atlassian.net/browse/TACHYON/

**Comment by netroby** [comment]
This is a feature request. not question

**Comment by yupeng9** [comment]
Thanks for the request. Opening a JIRA ticket on https://tachyon.atlassian.net/ is the preferred way, where it has better support to have discussions, and more people will see (and may help).
