### ISSUE TITLE
How can I intergeration CDH5.X????

### ISSUE THREAD

**Issue by jingwangfei** [amplab/tachyon#2432]
i install hdfs, spark and so on ....with CDH5;
so how can i install tachyon with cdh5?

**Comment by haoyuan** [comment]
Hi @jingwangfei ; Thanks for the interest. Please file and track issues in JIRA https://tachyon.atlassian.net/browse/TACHYON/ , and post questions in user forum: https://groups.google.com/forum/?fromgroups#!forum/tachyon-users

Thanks.
