### ISSUE TITLE
0.64版本  错误: 找不到或无法加载主类 tachyon.Format

### ISSUE THREAD

**Issue by guotong1988** [amplab/tachyon#959]
tachyon-0.6.4]# mvn -Dhadoop.version=2.3.0 clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Tachyon Project Parent
[INFO] Tachyon Project Core
[INFO] Tachyon Project Client
[INFO] Tachyon Project Assemblies
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Tachyon Project Parent 0.6.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tachyon-parent ---
[INFO] Deleting /home/cloudwave/tachyon-0.6.4/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ tachyon-parent ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle) @ tachyon-parent ---
[INFO] Starting audit...
Audit done.

[INFO] 
[INFO] --- license-maven-plugin:2.9:check (default) @ tachyon-parent ---
[INFO] Checking licenses...
[INFO] 
[INFO] >>> maven-source-plugin:2.3:jar (attach-sources) > generate-sources @ tachyon-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ tachyon-parent ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle) @ tachyon-parent ---
[INFO] Starting audit...
Audit done.

[INFO] 
[INFO] --- license-maven-plugin:2.9:check (default) @ tachyon-parent ---
[INFO] Checking licenses...
[INFO] 
[INFO] <<< maven-source-plugin:2.3:jar (attach-sources) < generate-sources @ tachyon-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.3:jar (attach-sources) @ tachyon-parent ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.9:jar (attach-javadoc) @ tachyon-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ tachyon-parent ---
[INFO] Installing /home/cloudwave/tachyon-0.6.4/pom.xml to /root/.m2/repository/org/tachyonproject/tachyon-parent/0.6.4/tachyon-parent-0.6.4.pom
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Tachyon Project Core 0.6.4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ tachyon ---
[INFO] Deleting /home/cloudwave/tachyon-0.6.4/core/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ tachyon ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle) @ tachyon ---
[INFO] Starting audit...
Audit done.

[INFO] 
[INFO] --- license-maven-plugin:2.9:check (default) @ tachyon ---
[INFO] Checking licenses...
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ tachyon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ tachyon ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 163 source files to /home/cloudwave/tachyon-0.6.4/core/target/classes
[WARNING] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/util/CommonUtils.java:[43,16] sun.misc.Cleaner是内部专用 API, 可能会在未来发行版中删除
[WARNING] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/util/CommonUtils.java:[44,18] sun.nio.ch.DirectBuffer是内部专用 API, 可能会在未来发行版中删除
[WARNING] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/util/CommonUtils.java:[126,7] sun.misc.Cleaner是内部专用 API, 可能会在未来发行版中删除
[WARNING] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/util/CommonUtils.java:[126,27] sun.nio.ch.DirectBuffer是内部专用 API, 可能会在未来发行版中删除
[INFO] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/UnderFileSystemHdfs.java: 某些输入文件使用或覆盖了已过时的 API。
[INFO] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/UnderFileSystemHdfs.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[INFO] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/thrift/ClientFileInfo.java: 某些输入文件使用了未经检查或不安全的操作。
[INFO] /home/cloudwave/tachyon-0.6.4/core/src/main/java/tachyon/thrift/ClientFileInfo.java: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ tachyon ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ tachyon ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 61 source files to /home/cloudwave/tachyon-0.6.4/core/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.14:test (default-test) @ tachyon ---
[INFO] Surefire report directory: /home/cloudwave/tachyon-0.6.4/core/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running tachyon.master.DependencyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.168 sec
Running tachyon.master.InodeFileTest
Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 sec
Running tachyon.master.EditLogOperationTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.024 sec
Running tachyon.master.RawTablesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec
Running tachyon.master.BlockInfoTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running tachyon.master.PinTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.962 sec
Running tachyon.master.InodeFolderTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
Running tachyon.master.JournalTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 294.573 sec
Running tachyon.master.MasterInfoTest
Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 316.419 sec
Running tachyon.master.MasterFaultToleranceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.624 sec
Running tachyon.master.MasterClientTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 22.481 sec
Running tachyon.PrefixListTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running tachyon.TachyonURITest
Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec
Running tachyon.PairTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running tachyon.UserInfoTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running tachyon.io.WriterReaderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running tachyon.io.UtilsTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running tachyon.command.UtilsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running tachyon.command.TFsShellTest
Tests run: 34, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 302.889 sec
Running tachyon.hadoop.fs.TestDFSIO
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 29.085 sec
Running tachyon.hadoop.UtilsTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running tachyon.hadoop.GlusterFSTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running tachyon.hadoop.TFSTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.582 sec
Running tachyon.hadoop.HdfsFileInputStreamTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.662 sec
Running tachyon.util.CommonUtilsTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.595 sec
Running tachyon.util.UnderfsUtilsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.503 sec
Running tachyon.util.NetworkUtilsTest
Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE!
replaceHostNameTest(tachyon.util.NetworkUtilsTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<hdfs://localhost.localdomain:9000/dir> but was:<hdfs://localhost:9000/dir>
        at org.junit.Assert.fail(Assert.java:93)
        at org.junit.Assert.failNotEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:128)
        at org.junit.Assert.assertEquals(Assert.java:147)
        at tachyon.util.NetworkUtilsTest.replaceHostNameTest(NetworkUtilsTest.java:40)

resolveHostNameTest(tachyon.util.NetworkUtilsTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<localhost[.localdomain]> but was:<localhost[]>
        at org.junit.Assert.assertEquals(Assert.java:125)
        at org.junit.Assert.assertEquals(Assert.java:147)
        at tachyon.util.NetworkUtilsTest.resolveHostNameTest(NetworkUtilsTest.java:48)

getFqdnHostTest(tachyon.util.NetworkUtilsTest)  Time elapsed: 0 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<localhost[.localdomain]> but was:<localhost[]>
        at org.junit.Assert.assertEquals(Assert.java:125)
        at org.junit.Assert.assertEquals(Assert.java:147)
        at tachyon.util.NetworkUtilsTest.getFqdnHostTest(NetworkUtilsTest.java:53)

Running tachyon.worker.WorkerServiceHandlerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 38.15 sec
Running tachyon.worker.BlockHandlerLocalTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.647 sec
Running tachyon.worker.WorkerStorageTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 55.667 sec
Running tachyon.worker.hierarchy.EvictStrategyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.822 sec
Running tachyon.worker.hierarchy.HierarchyStoreTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.845 sec
Running tachyon.worker.hierarchy.AllocateStrategyTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.068 sec
Running tachyon.worker.hierarchy.StorageTierTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.933 sec
Running tachyon.worker.hierarchy.StorageDirTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.511 sec
Running tachyon.worker.DataServerTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 125.683 sec
Running tachyon.conf.UtilsTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running tachyon.UnderFileSystemTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running tachyon.client.LocalBlockInStreamTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.14 sec
Running tachyon.client.TachyonFSTest
Tests run: 30, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 8.2 sec <<< FAILURE!
toStringTest(tachyon.client.TachyonFSTest)  Time elapsed: 0.001 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<tachyon://localhost[]/127.0.0.1:19998> but was:<tachyon://localhost[.localdomain]/127.0.0.1:19998>
        at org.junit.Assert.assertEquals(Assert.java:125)
        at org.junit.Assert.assertEquals(Assert.java:147)
        at tachyon.client.TachyonFSTest.toStringTest(TachyonFSTest.java:355)

Running tachyon.client.TachyonFileUpdateTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.818 sec
Running tachyon.client.FileInStreamTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.627 sec
Running tachyon.client.TachyonFileTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 47.559 sec
Running tachyon.client.table.RawTableTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 60.029 sec
Running tachyon.client.table.RawColumnTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.014 sec
Running tachyon.client.BlockInStreamTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.122 sec
Running tachyon.client.FileOutStreamTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 16.663 sec
Running tachyon.client.RemoteBlockInStreamTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.722 sec
Running tachyon.retry.ExponentialBackoffRetryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Results :

Failed tests: 
  NetworkUtilsTest.replaceHostNameTest:40 expected:<hdfs://localhost.localdomain:9000/dir> but was:<hdfs://localhost:9000/dir>
  NetworkUtilsTest.resolveHostNameTest:48 expected:<localhost[.localdomain]> but was:<localhost[]>
  NetworkUtilsTest.getFqdnHostTest:53 expected:<localhost[.localdomain]> but was:<localhost[]>
  TachyonFSTest.toStringTest:355 expected:<tachyon://localhost[]/127.0.0.1:19998> but was:<tachyon://localhost[.localdomain]/127.0.0.1:19998>

Tests run: 351, Failures: 4, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Tachyon Project Parent ............................. SUCCESS [  4.509 s]
[INFO] Tachyon Project Core ............................... FAILURE [25:42 min]
[INFO] Tachyon Project Client ............................. SKIPPED
[INFO] Tachyon Project Assemblies ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25:47 min
[INFO] Finished at: 2015-05-25T16:45:23+08:00
[INFO] Final Memory: 51M/1365M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test (default-test) on project tachyon: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/cloudwave/tachyon-0.6.4/core/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tachyon

**Comment by apc999** [comment]
Hi

This is due to the fact that the local loopback address 127.0.0.1 is resolved to "localhost.localdomain" in your server while we are expecting it to be "localhost". Doublecheck your /etc/hosts setting, or share with us more your server info?

btw, to report issues of Tachyon, openning a JIRA on https://tachyon.atlassian.net/ is the preferred way, where it has better support to have discussion, and more people will see (and may help)

- Bin

**Comment by haoyuan** [comment]
@guotong1988 

Could you please post these to our user mailing list ( https://groups.google.com/forum/?fromgroups#!forum/tachyon-users ) ? Thanks.

https://github.com/amplab/tachyon/issues/329

**Comment by guotong1988** [comment]
Thanks  .  OK

**Comment by mysterytree** [comment]
@apc999  你好 问下tachyon用的是jvm之外的内存的话会不会抢占机器其他framework的资源？
