### ISSUE TITLE
Tachyon's performance question

### ISSUE THREAD

**Issue by Kira-Yang** [amplab/tachyon#968]
We want to use Tachyon, and we evaluate its performance with TestDFSIO.java in hadoop-mapreduce-client-jobclient-2.6.0-tests.jar, we find that Tachyon was a bit better than HDFS with cache in local sequence read and write, was equal in remote read, and was worse in local random read and backward read. Can we improve Tachyon's pure read and write performance with modify some configuration items or other means, or is our test method incorrect?
<h4>Test Result</h4>
1 Initial local read, files 24*1GB
<table>
<tr><th>unit: s</th><th>sequence read</th><th>random read</th><th>backward read</th></tr>
<tr><td>Tachyon on HDFS</td><td>144.86</td><td>failed</td><td>failed</td></tr>
<tr><td>Tachyon on own FS</td><td>78.357</td><td>245.057(the file read wasn't in memory)</td><td>failed</td></tr>
<tr><td>HDFS</td><td>128.598</td><td>167.697</td><td>329.518</td></tr>
</table>
2 Local read with files cache in memory, files 24*1GB
<table>
<tr><th>unit: s</th><th>sequence read</th><th>random read</th><th>backward read</th></tr>
<tr><td>Tachyon</td><td>11.649</td><td>52.79</td><td>46.877</td></tr>
<tr><td>HDFS</td><td>15.6</td><td>27.889</td><td>27.412</td></tr>
</table>
3 Remote read, files 12*1GB
<table>
<tr><th>unit: s</th><th>times</th></tr>
<tr><td>Tachyon</td><td>1113.811</td></tr>
<tr><td>HDFS</td><td>1078.591</td></tr>
</table>
4 Write, files 24*1GB, Tachyon's write type: CACHE_THROUGH, HDFS's dfs.replication: 1
<table>
<tr><th>unit: s</th><th>times</th></tr>
<tr><td>Tachyon on HDFS</td><td>99.39</td></tr>
<tr><td>Tachyon on own FS</td><td>73.042</td></tr>
<tr><td>HDFS</td><td>76.212</td></tr>
</table>
<h4>Test Environment</h4>
Master: blade server with CPU 1.9GHz\*24, RAM 16GB\*2, running NameNode and DataNode, Tachyon master and Tachyon worker
Slave1: blade server with CPU 1.9GHz\*24, RAM 16GB\*1, running DataNode, Tachyon worker
Slave2: blade server with CPU 1.9GHz\*24, RAM 16GB\*1, running DataNode, Tachyon worker
Software version: Tachyon 0.6.3, Hadoop 2.6.0
<h4>Test Method</h4>
We modified the TestDFSIO.java adding a parameter fs to input our tachyon fs, and test Tachyon like this, refer to <a href="https://github.com/Kira-Yang/tachyon-test">my github</a> for detail:
bin/hadoop jar share/hadoop/mapreduce/hadoop-mapreduce-client-jobclient-2.6.0-tests.jar TestDFSIO -libjars /home/michael/tachyon/tachyon-0.6.3/client/target/tachyon-client-0.6.3-jar-with-dependencies.jar -write -nrFiles 36 -fileSize 1000 -fs tachyon://master:19998

**Comment by calvinjia** [comment]
@Kira-Yang 

Could you please post questions like this to our [user mailing list](https://groups.google.com/forum/?fromgroups#!forum/tachyon-users)?

See #329

**Comment by Kira-Yang** [comment]
OK, I have post it at the forum
